TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

DISTFILES += \
    include/log4cplus/config/stamp-h2 \
    include/log4cplus/stamp-h1

HEADERS += \
    include/curl/curl.h \
    include/curl/curlbuild.h \
    include/curl/curlrules.h \
    include/curl/curlver.h \
    include/curl/easy.h \
    include/curl/mprintf.h \
    include/curl/multi.h \
    include/curl/stdcheaders.h \
    include/curl/typecheck-gcc.h \
    include/gumbo/attribute.h \
    include/gumbo/char_ref.h \
    include/gumbo/error.h \
    include/gumbo/gumbo.h \
    include/gumbo/insertion_mode.h \
    include/gumbo/parser.h \
    include/gumbo/string_buffer.h \
    include/gumbo/string_piece.h \
    include/gumbo/tag_enum.h \
    include/gumbo/tag_gperf.h \
    include/gumbo/tag_sizes.h \
    include/gumbo/tag_strings.h \
    include/gumbo/token_type.h \
    include/gumbo/tokenizer.h \
    include/gumbo/tokenizer_states.h \
    include/gumbo/utf8.h \
    include/gumbo/util.h \
    include/gumbo/vector.h \
    include/json/allocator.h \
    include/json/assertions.h \
    include/json/autolink.h \
    include/json/config.h \
    include/json/features.h \
    include/json/forwards.h \
    include/json/json.h \
    include/json/reader.h \
    include/json/value.h \
    include/json/version.h \
    include/json/writer.h \
    include/log4cplus/boost/deviceappender.hxx \
    include/log4cplus/config/defines.hxx \
    include/log4cplus/config/defines.hxx.in \
    include/log4cplus/config/macosx.h \
    include/log4cplus/config/win32.h \
    include/log4cplus/config/windowsh-inc.h \
    include/log4cplus/helpers/appenderattachableimpl.h \
    include/log4cplus/helpers/connectorthread.h \
    include/log4cplus/helpers/fileinfo.h \
    include/log4cplus/helpers/lockfile.h \
    include/log4cplus/helpers/loglog.h \
    include/log4cplus/helpers/logloguser.h \
    include/log4cplus/helpers/pointer.h \
    include/log4cplus/helpers/property.h \
    include/log4cplus/helpers/queue.h \
    include/log4cplus/helpers/sleep.h \
    include/log4cplus/helpers/snprintf.h \
    include/log4cplus/helpers/socket.h \
    include/log4cplus/helpers/socketbuffer.h \
    include/log4cplus/helpers/stringhelper.h \
    include/log4cplus/helpers/thread-config.h \
    include/log4cplus/helpers/timehelper.h \
    include/log4cplus/internal/cygwin-win32.h \
    include/log4cplus/internal/env.h \
    include/log4cplus/internal/internal.h \
    include/log4cplus/internal/socket.h \
    include/log4cplus/spi/appenderattachable.h \
    include/log4cplus/spi/factory.h \
    include/log4cplus/spi/filter.h \
    include/log4cplus/spi/loggerfactory.h \
    include/log4cplus/spi/loggerimpl.h \
    include/log4cplus/spi/loggingevent.h \
    include/log4cplus/spi/objectregistry.h \
    include/log4cplus/spi/rootlogger.h \
    include/log4cplus/thread/impl/syncprims-cxx11.h \
    include/log4cplus/thread/impl/syncprims-impl.h \
    include/log4cplus/thread/impl/syncprims-pmsm.h \
    include/log4cplus/thread/impl/syncprims-pthreads.h \
    include/log4cplus/thread/impl/syncprims-win32.h \
    include/log4cplus/thread/impl/threads-impl.h \
    include/log4cplus/thread/impl/tls.h \
    include/log4cplus/thread/syncprims-pub-impl.h \
    include/log4cplus/thread/syncprims.h \
    include/log4cplus/thread/threads.h \
    include/log4cplus/appender.h \
    include/log4cplus/asyncappender.h \
    include/log4cplus/clfsappender.h \
    include/log4cplus/clogger.h \
    include/log4cplus/config.h \
    include/log4cplus/config.h.cmake.in \
    include/log4cplus/config.h.in \
    include/log4cplus/config.hxx \
    include/log4cplus/configurator.h \
    include/log4cplus/consoleappender.h \
    include/log4cplus/fileappender.h \
    include/log4cplus/fstreams.h \
    include/log4cplus/hierarchy.h \
    include/log4cplus/hierarchylocker.h \
    include/log4cplus/layout.h \
    include/log4cplus/log4judpappender.h \
    include/log4cplus/logger.h \
    include/log4cplus/loggingmacros.h \
    include/log4cplus/loglevel.h \
    include/log4cplus/mdc.h \
    include/log4cplus/msttsappender.h \
    include/log4cplus/ndc.h \
    include/log4cplus/nteventlogappender.h \
    include/log4cplus/nullappender.h \
    include/log4cplus/qt4debugappender.h \
    include/log4cplus/qt5debugappender.h \
    include/log4cplus/socketappender.h \
    include/log4cplus/streams.h \
    include/log4cplus/syslogappender.h \
    include/log4cplus/tchar.h \
    include/log4cplus/tracelogger.h \
    include/log4cplus/tstring.h \
    include/log4cplus/version.h \
    include/log4cplus/win32consoleappender.h \
    include/log4cplus/win32debugappender.h \
    include/zeromq/zmq.h \
    include/zeromq/zmq_utils.h
